### PR TITLE
 publish ports and API port.

### PR DESCRIPTION
**Pull request by contato318**
Hi!

I added the option to publish ports (we use them a lot here) and the option to set the port of the api (useful for several k3s running)

I hope it has some use for you.

### CODE REVIEW

**Comment by contato318** [comment]
Add check req (docker, k3d, kubectl, ...)

**Comment by nicks** [comment]
Hi Dirceu! Thanks for the PR. I understand why you want this change. 

Our short-term goal was to give people a simple script that they can fork and customize  to set up k3d themselves with Tilt.

Our long-term goal is for this script to go away, and to get changes into k3d to make a simple option with the k3d CLI.

I really don't want this to become a big wrapper script with lots of options and safety checks. Those checks should really live in k3d, not here.

Given that, how would you like to proceed? I would be fine with something like a K3D_EXTRA_FLAGS env variable that just let you pass extra flags to k3d. I'd also be fine with the tool existence checks. But the `port_is_ok` check and more fine-grained API is a bit much.

**Comment by contato318** [comment]
I vote for K3D_EXTRA_FLAGS :)

I will do some tests here.

**Comment by nicks** [comment]
i'm going to archive this repo. there's not really a good reason to maintain this script, now that k3d supports this natively.

**Pull request closed without merging**
